name: register issues in Kanban

on:
  issues:
    types: [opened]

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: kaihatsu
          column: yaru
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
